parameters:
    orotracker_issue.form.type.issue.class:    Oro\Bundle\TrackerBundle\Form\Type\IssueType
#    orocrm_task.form.type.task_api.class:           OroCRM\Bundle\TaskBundle\Form\Type\TaskApiType
    orotracker_issue.form.handler.issue.class: Oro\Bundle\TrackerBundle\Form\Handler\IssueHandler
#    orocrm_task.form.handler.task_api.class:        OroCRM\Bundle\TaskBundle\Form\Handler\TaskApiHandler
#    orocrm_task.manager.api.class:                  Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager

services:
    orotracker_issue.form.issue.task:
        class: %orotracker_issue.form.type.issue.class%
        tags:
            - { name: form.type, alias: orotracker_issue }

    orotracker_issue.form:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments:
            - 'orotracker_issue'
            - 'orotracker_issue'

    orotracker_issue.form.handler.issue:
        class: %orotracker_issue.form.handler.issue.class%
        scope: request
        arguments:
            - @orotracker_issue.form
            - @request
            - @doctrine.orm.entity_manager
            - @oro_activity.manager
            - @oro_entity.routing_helper
