oro_menu_config:
    items:
        issue_tab:
            label: 'oro.tracker.issue.entity_plural_label'
            uri:   '#'
            extras:
                position: 300
        issue_link:
            label: 'oro.tracker.issue.entity_plural_label'
            route: orotracker_issue_index
    tree:
        application_menu:
            children:
              issue_tab:
                children:
                  issue_link: ~