placeholders:
    view_content_data_additional_information:
        items:
            orotracker_user_issue: ~

    view_navButtons_before:
        items:
            orocrm_my_tasks_button: ~

items:
    orocrm_my_tasks_button:
        template: OroTrackerBundle:User:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: orotracker_issue_create
    orotracker_user_issue:
        template: OroTrackerBundle:User:userIssue.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: orotracker_issue_view