placeholders:
    view_content_data_additional_information:
        items:
            oro_tracker_user_issue: ~

    view_navButtons_before:
        items:
            oro_tracker_my_issue_button: ~

items:
    oro_tracker_user_issue:
        template: OroTrackerBundle:User:userIssue.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: orotracker_issue_view
    oro_tracker_my_issue_button:
        template: OroTrackerBundle:User:createIssueButton.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
        acl: orotracker_issue_create
