definitions:
  add_issue_collaboration_by_event_issue:
    label: 'Mark user involved in issue as a collaborator'
    enabled: true
    entity: Oro\Bundle\TrackerBundle\Entity\Issue
    actions_configuration:
      - @call_method:
          object: $.data
          method: addCollaborator
          method_parameters: [$assignee]
      - @call_method:
          object: $.data
          method: addCollaborator
          method_parameters: [$owner]

  add_issue_collaboration_by_event_note:
      label: 'Mark issue commenter as a collaborator'
      enabled: true
      entity: Oro\Bundle\NoteBundle\Entity\Note
      actions_configuration:
          - @call_method:
                object: $.data
                attribute: $.isIssue
                method: supportTarget
                method_parameters: ['Issue']
          - @create_datetime:
                condition:
                    @true: $.isIssue
                attribute: $.data.target.updatedAt
          - @call_method:
              condition:
                  @true: $.isIssue
              object: $.data.target
              method: addCollaborator
              method_parameters: [$owner]



triggers:
    add_issue_collaboration_by_event_issue:
        -
            event: create
            queued: false
        -
            event: update
            field: assignee
            queued: false
        -
            event: update
            field: owner
            queued: false

    add_issue_collaboration_by_event_note:
        -
            event: create
            queued: false