workflows:
    issue_flow:
        attributes:
            issue_resolution:
                label: 'Resolution'
                type: entity
                options:
                    class: Oro\Bundle\TrackerBundle\Entity\Resolution
