workflows:
    issue_flow:
        transitions:
            start_progress:
                label: 'Start progress'
                step_to: in_progress
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-play'
                transition_definition: start_progress_definition
            stop_progress:
                label: 'Stop progress'
                step_to: open
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-stop'
                transition_definition: stop_progress_definition
            close:
                label: 'Close'
                step_to: closed
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: closed_definition
                form_options:                               # options which will be passed to form type of transition
                    attribute_fields:                       # list of attribute fields which will be shown
                        issue_resolution:                   # attribute name
                            form_type: entity
                            options:                        # list of form field options
                                class: Oro\Bundle\TrackerBundle\Entity\Resolution
                                property: label
                                required: true
            resolve:
                label: 'Resolve'
                step_to: resolved
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-ok'
                transition_definition: resolve_definition
                form_options:                               # options which will be passed to form type of transition
                    attribute_fields:                       # list of attribute fields which will be shown
                        issue_resolution:                   # attribute name
                            form_type: entity
                            options:                        # list of form field options
                                class: Oro\Bundle\TrackerBundle\Entity\Resolution
                                property: label
                                required: true

            reopen:
                label: 'Reopen'
                step_to: reopened
                #is_unavailable_hidden: true
                frontend_options:
                    icon: 'icon-edit'
                transition_definition: reopened_definition
                form_options:                                 # options which will be passed to form type of transition
                    attribute_fields:                       # list of attribute fields which will be shown
                        issue_resolution:                   # attribute name
                            form_type: entity
                            options:                        # list of form field options
                                class: Oro\Bundle\TrackerBundle\Entity\Resolution
                                property: label
                                required: true